steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '$_IMAGE_NAME', '-f', 'src/services/pii_tokenizer/Dockerfile', '.']
images:
- '$_IMAGE_NAME'
options:
  logging: CLOUD_LOGGING_ONLY
